title = 'run-marathon'
description = 'Simplify and manage your serverless container deployments. Like docker-compose but for Cloud Run.'
url = 'https://github.com/adrianchifor/run-marathon'
version = '0.3.2'
author = 'Adrian Chifor'
author_email = 'me@adrianchifor.com'
license = 'Apache License 2.0'
